# docker continuous integration
# run tests
---
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v1

      - name: Install test runner
        run: python3 -m pip install tox

      - name: Run tests
        run: tox
